---
title: Numbers - introduction 
author: Erika Duan
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    toc_depth: 2
    math_method:
      engine: webtex
      url: https://latex.codecogs.com/svg.format?
---

```{r setup, include=FALSE}
# Set up global environment configuration --------------------------------------
knitr::opts_chunk$set(echo=TRUE, results='hide', fig.align='center')
knitr::knit_engines$set(python = reticulate::eng_python)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Load required R packages -----------------------------------------------------
if (!require("pacman")) install.packages("pacman")
p_load(tidyverse,
       RColorBrewer,
       scales,
       reticulate,
       JuliaCall,
       knitr)

# Check version of Python used by reticulate -----------------------------------
reticulate::py_config()

# Set up Julia for automatic type conversion -----------------------------------
julia <- julia_setup()
```


## Testing 

$\frac{1}{\pi}$ is a fraction. Testing